from video_processing.video import Video
from video_processing.video_magnification_algorithm import Video_Magnification
from video_processing.complexity_pursuit_functions import return_mask
from video_processing.pca_functions import apply_pca
